packages:
  - "apps/*"
  - "apps/web/.react-email"
  - "packages/*"
  - "packages/embeds/*"
pnpm:
  allowedNonApprovedScripts:
    - '@prisma/client'
    - '@prisma/engines'
    - '@swc/core'
    - 'esbuild'
    - 'prisma'
    - 'protobufjs'
    - 'sharp'
    - 'sqlite3'
