packages:
  - "apps/*"
  - "apps/web/.react-email"
  - "packages/*"
  - "packages/embeds/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "esbuild"
  - "prisma"
  - "protobufjs"
  - "sharp"
  - "sqlite3"
  - "better-sqlite3"
